---

- name: collect secondary bigiq ip address
  set_fact:
    secondary_bigiq_address: "{{ hostvars[item].ansible_host }}"
  with_items: "{{ groups['all'] }}"
  when: not hostvars[item].haprimary | default(True)|bool

- name: Setup provider
  set_fact:
    provider:
      server: "{{ bigiq_onboard_server }}"
      server_port: "{{ bigiq_onboard_server_port }}"
      user: "{{ bigiq_onboard_user }}"
      password: "{{ bigiq_onboard_password }}"
      validate_certs: "{{ bigiq_onboard_validate_certs }}"
      transport: "{{ bigiq_onboard_transport }}"

- name: Wait for BIG-IQ to be available
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
  register: system_status
  until: system_status is success and system_status.json.available|bool
  retries: 15
  delay: 15

- name: Get authentication token
  block:
    - name: Get authentication token 1
      uri:
        url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
        method: POST
        timeout: "{{ bigiq_onboard_timeout }}"
        validate_certs: "{{ bigiq_onboard_validate_certs }}"
        body:
          username: "{{ bigiq_onboard_user }}"
          password: "{{ bigiq_onboard_password }}"
        body_format: json
      register: authtokenonb
  rescue:
    # Due to TMOS change in 8.0, in case the admin password been reset already, use the new one (re-try)
    - name: Get authentication token 2
      uri:
        url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
        method: POST
        timeout: "{{ bigiq_onboard_timeout }}"
        validate_certs: "{{ bigiq_onboard_validate_certs }}"
        body:
          username: "{{ bigiq_onboard_user }}"
          password: "{{ bigiq_onboard_new_admin_password }}"
        body_format: json
      register: authtokenonb

# Due to TMOS change in 8.0, need to set new admin password which is expired by default
- name: Reset expired password starting BIG-IQ 8.0
  include_tasks: setup-reset-expired-password8_0.yaml
  when:
    - authtokenonb.json.expired is defined
    - authtokenonb.json.expired|bool
    - system_status.json.build is defined
    - system_status.json.build is not match("^\D+.[7-].[0-].*$") and
      system_status.json.build is not match("^\D+.[6-].[0-1].*$") and
      system_status.json.build is not match("^\D+.[7-].[1-].*$")

- name: Set the token fact if authentication succeeded
  set_fact:
    f5_auth_token: "{{ authtokenonb.json.token.token }}"
  when: authtokenonb is success

- name: Get BIGIQ System Info
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: system_status
  until: system_status is success and system_status.json.available|bool
  retries: 10
  delay: 6

- name: Test authentication (BIGIQ < 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/echo"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  when: 
    - system_status.json.build is defined
    - system_status.json.build is match("^\D+.[7-].[0-].*$") or
      system_status.json.build is match("^\D+.[6-].[0-1].*$")

- name: Test authentication (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/launch/status"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  when:
    - system_status.json.build is defined
    - system_status.json.build is not match("^\D+.[7-].[0-].*$") and
      system_status.json.build is not match("^\D+.[6-].[0-1].*$")
    - not system_status.json.isSystemSetup|bool


- name: Check if system is setup (BIGIQ < 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/setup"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: setup
  when: 
    - system_status.json.build is defined
    - system_status.json.build is match("^\D+.[7-].[0-].*$") or 
      system_status.json.build is match("^\D+.[6-].[0-1].*$")

- name: Check if system is setup (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/config"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: setup
  when:
    - system_status.json.build is defined
    - system_status.json.build is not match("^\D+.[7-].[0-].*$") and
      system_status.json.build is not match("^\D+.[6-].[0-1].*$")
    - not system_status.json.isSystemSetup|bool

- name: include setup-main.yaml (BIGIQ < 7.1)
  include_tasks: setup-main.yaml
  when: 
    - system_status.json.build is defined
    - system_status.json.build is match("^\D+.[7-].[0-].*$") or 
      system_status.json.build is match("^\D+.[6-].[0-1].*$")

- name: include setup-main-bigiq7_1.yaml (BIGIQ = 7.1)
  include_tasks: setup-main-bigiq7_1.yaml
  when:
    - system_status.json.build is defined 
    - system_status.json.build is match("^\D+.[7-].[1-].*$")

# Due to TMOS change in 8.0, need to use the new password to renew token to launch
- name: include setup-main-bigiq7_1.yaml (BIGIQ >= 7.2)
  include_tasks: setup-main-bigiq7_1.yaml
  vars:
    bigiq_onboard_password: "{{ bigiq_onboard_new_admin_password }}"
  when:
    - system_status.json.build is defined 
    - system_status.json.build is not match("^\D+.[7-].[0-].*$") and
      system_status.json.build is not match("^\D+.[6-].[0-1].*$") and
      system_status.json.build is not match("^\D+.[7-].[1-].*$")