---

- name: Set new admin password
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/reset-expired-password"
    method: POST
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    body:
      username: "admin"
      currentPassword: "{{ bigiq_onboard_old_admin_password }}"
      newPassword: "{{ bigiq_onboard_new_admin_password }}"
    body_format: json

- name: Get authentication token using new admin password
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
    method: POST
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    body:
      username: "admin"
      password: "{{ bigiq_onboard_new_admin_password }}"
    body_format: json
  register: authtokenonb