---

- name: Get management address details (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/address"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: ez
  when: bigiq_onboard_discovery_address == provider.server

- name: Set discovery address (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/address"
    method: PATCH
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body:
      discoveryAddress: "{{ ez.json.managementIpAddress[:-3] }}"
    body_format: json
  when: bigiq_onboard_discovery_address == provider.server

- name: Check discovery address is correct (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/address"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: result
  until: ez.json.managementIpAddress[:-3] == result.json.discoveryAddress
  retries: 5
  delay: 3
  when: bigiq_onboard_discovery_address == provider.server

############ from here when Discovery IP is defined

- include_tasks: setup-network7_1.yaml
  when: bigiq_onboard_discovery_address != provider.server

- name: Set discovery address to self-ip (BIGIQ >= 7.1)
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/setup/address/self-ip"
    method: PATCH
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body:
      address: "{{ bigiq_onboard_discovery_address }}"
      vlan: discovery
      iface: "1.1"
    body_format: json
  when: bigiq_onboard_discovery_address != provider.server
